//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.20 at 01:50:07 PM GMT 
//


package com.discover.neural.engine.jaxb.network;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for abstract-functionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="abstract-functionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="type" use="required" type="{http://neural.discover.com/enumerations}standard_functions" />
 *       &lt;attribute name="bean-name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="bean-parameters" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="expression" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="atomic-value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="atomic-value-type" type="{http://neural.discover.com/enumerations}atomic_value_types" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "abstract-functionType")
@XmlSeeAlso({
    ActivationFunctionType.class,
    SignalFunctionType.class
})
public abstract class AbstractFunctionType {

    @XmlAttribute(name = "type", required = true)
    protected StandardFunctions type;
    @XmlAttribute(name = "bean-name")
    protected String beanName;
    @XmlAttribute(name = "bean-parameters")
    protected String beanParameters;
    @XmlAttribute(name = "expression")
    protected String expression;
    @XmlAttribute(name = "atomic-value")
    protected String atomicValue;
    @XmlAttribute(name = "atomic-value-type")
    protected AtomicValueTypes atomicValueType;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link StandardFunctions }
     *     
     */
    public StandardFunctions getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link StandardFunctions }
     *     
     */
    public void setType(StandardFunctions value) {
        this.type = value;
    }

    /**
     * Gets the value of the beanName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeanName() {
        return beanName;
    }

    /**
     * Sets the value of the beanName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeanName(String value) {
        this.beanName = value;
    }

    /**
     * Gets the value of the beanParameters property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeanParameters() {
        return beanParameters;
    }

    /**
     * Sets the value of the beanParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeanParameters(String value) {
        this.beanParameters = value;
    }

    /**
     * Gets the value of the expression property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpression() {
        return expression;
    }

    /**
     * Sets the value of the expression property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpression(String value) {
        this.expression = value;
    }

    /**
     * Gets the value of the atomicValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAtomicValue() {
        return atomicValue;
    }

    /**
     * Sets the value of the atomicValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAtomicValue(String value) {
        this.atomicValue = value;
    }

    /**
     * Gets the value of the atomicValueType property.
     * 
     * @return
     *     possible object is
     *     {@link AtomicValueTypes }
     *     
     */
    public AtomicValueTypes getAtomicValueType() {
        return atomicValueType;
    }

    /**
     * Sets the value of the atomicValueType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AtomicValueTypes }
     *     
     */
    public void setAtomicValueType(AtomicValueTypes value) {
        this.atomicValueType = value;
    }

}
