//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.20 at 01:50:07 PM GMT 
//


package com.discover.neural.engine.jaxb.network;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.discover.neural.engine.jaxb.network package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Network_QNAME = new QName("http://neural.discover.com/networks", "network");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.discover.neural.engine.jaxb.network
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NetworkType }
     * 
     */
    public NetworkType createNetworkType() {
        return new NetworkType();
    }

    /**
     * Create an instance of {@link InputSignalsType }
     * 
     */
    public InputSignalsType createInputSignalsType() {
        return new InputSignalsType();
    }

    /**
     * Create an instance of {@link NeuronType }
     * 
     */
    public NeuronType createNeuronType() {
        return new NeuronType();
    }

    /**
     * Create an instance of {@link SignalSourceType }
     * 
     */
    public SignalSourceType createSignalSourceType() {
        return new SignalSourceType();
    }

    /**
     * Create an instance of {@link ActivationFunctionType }
     * 
     */
    public ActivationFunctionType createActivationFunctionType() {
        return new ActivationFunctionType();
    }

    /**
     * Create an instance of {@link SynapseType }
     * 
     */
    public SynapseType createSynapseType() {
        return new SynapseType();
    }

    /**
     * Create an instance of {@link NeuronsType }
     * 
     */
    public NeuronsType createNeuronsType() {
        return new NeuronsType();
    }

    /**
     * Create an instance of {@link InputSignalType }
     * 
     */
    public InputSignalType createInputSignalType() {
        return new InputSignalType();
    }

    /**
     * Create an instance of {@link SignalFunctionType }
     * 
     */
    public SignalFunctionType createSignalFunctionType() {
        return new SignalFunctionType();
    }

    /**
     * Create an instance of {@link SynapsesType }
     * 
     */
    public SynapsesType createSynapsesType() {
        return new SynapsesType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NetworkType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://neural.discover.com/networks", name = "network")
    public JAXBElement<NetworkType> createNetwork(NetworkType value) {
        return new JAXBElement<NetworkType>(_Network_QNAME, NetworkType.class, null, value);
    }

}
