//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.20 at 01:50:07 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://neural.discover.com/networks", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.discover.neural.engine.jaxb.network;
