//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.20 at 01:50:07 PM GMT 
//


package com.discover.neural.engine.jaxb.network;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for standard_functions.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="standard_functions">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="identity"/>
 *     &lt;enumeration value="custom"/>
 *     &lt;enumeration value="expression"/>
 *     &lt;enumeration value="atomic"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "standard_functions", namespace = "http://neural.discover.com/enumerations")
@XmlEnum
public enum StandardFunctions {

    @XmlEnumValue("identity")
    IDENTITY("identity"),
    @XmlEnumValue("custom")
    CUSTOM("custom"),
    @XmlEnumValue("expression")
    EXPRESSION("expression"),
    @XmlEnumValue("atomic")
    ATOMIC("atomic");
    private final String value;

    StandardFunctions(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StandardFunctions fromValue(String v) {
        for (StandardFunctions c: StandardFunctions.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
